apiVersion: apps/v1
kind: Deployment
metadata:
{{ if eq .Values.stage "release" }}
  namespace: prod
{{ else }}
  namespace: uat
{{ end }}
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        imagePullPolicy: Always
        image: galvezlj/{{ .Values.name }}:{{ .Values.stage }}
        ports:
        - containerPort: 3000
        env:
{{ if eq .Values.stage "release" }}
        - name: DATA_FILE
          value: Questions.json
{{ else }}
        - name: DATA_FILE
          value: Questions-test.json
{{ end }}
