apiVersion: v1
kind: Service
metadata:
  name: one2onetool-service
{{ if eq .Values.stage "release" }}
  namespace: prod
{{ else }}
  namespace: staging
{{ end }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: one2onetool
  type: LoadBalancer
