apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
{{ if eq .Values.stage "release" }}
  namespace: prod
{{ else }}
  namespace: uat
{{ end }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer
