apiVersion: v1
kind: Service
metadata:
  name: one2onetool-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: one2onetool
  type: LoadBalancer
