# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ staging ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  # build:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
    - name: Setup Environment
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/one2onetool:${{ env.BRANCH }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - run: pwd
    - run: ls
    - run: which aws-iam-authenticator
    - name: Trigger deploy
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f deploy/deploy.yaml -f deploy/service.yaml

  # alert:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        to: andy.galvez@shopback.com,andy_galvez@yahoo.com
        from: Alert          